# Generated by Django 2.0.5 on 2018-06-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew_trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewtrips',
            name='brewery_city',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brewtrips',
            name='latitude',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='brewtrips',
            name='longitude',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
