# Generated by Django 2.0.5 on 2018-06-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew_trips', '0002_auto_20180619_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewtrips',
            name='favorite_brewery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='brewtrips',
            name='brewery_city',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
